[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "protossl"
authors = [
  { name="Steven Song", email="songs1@uchicago.edu" },
  { name="Sahil Sethi", email="sethis@uchicago.edu" },
]
description = "ProtoSSL: Interpretable Prototype Learning from Unlabeled Time-Series Data"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version", "dependencies"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Steven/ProtoSSL"
Issues = "https://github.com/Steven/ProtoSSL/issues"

[tool.hatch.version]
path = "protossl/__init__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]
