target_columns:
  "LVEF Lo": "lvef_lte_45_flag"
  "LVWT Hi": "lvwt_gte_13_flag"
  "AS": "aortic_stenosis_moderate_or_greater_flag"
  "AR": "aortic_regurgitation_moderate_or_greater_flag"
  "MR": "mitral_regurgitation_moderate_or_greater_flag"
  "TR": "tricuspid_regurgitation_moderate_or_greater_flag"
  "PR": "pulmonary_regurgitation_moderate_or_greater_flag"
  "RVD": "rv_systolic_dysfunction_moderate_or_greater_flag"
  "PEff": "pericardial_effusion_moderate_large_flag"
  "PASP Hi": "pasp_gte_45_flag"
  "TRV Hi": "tr_max_gte_32_flag"
  "SHD": "shd_moderate_or_greater_flag"
composite_target: "SHD"
