program: pass_pclr.trainer
name: ProtoECGNet-HEEDB-1D-Global
# name: ProtoECGNet-HEEDB-2D-Global
# name: ProtoECGNet-HEEDB-2D-Partial
method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  model.n_prototypes_per_label:
    distribution: int_uniform
    min: 5
    max: 25
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - "--config"
  - "1D-global.yaml"
  # - "2D-global.yaml"
  # - "2D-partial.yaml"
  - "--trainer.logger.save_dir"
  - "/home/songs1/outputs-tune-heedb"
  - "--data.dataset_path"
  - "/opt/gpudata/ecg/heedb"
  - ${args}
