# lightning.pytorch==2.6.0
seed_everything: 42
trainer:
  devices: 1
  precision: 32
  logger:
    class_path: protossl.lightning_utils.StrictWandbLogger
    init_args:
      project: ProtoSSL-Audio
      # save_dir: /path/to/runs/
      # name: exp-name
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        patience: 10 # check reduce lr on plateau
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_last: True
    - class_path: PredictionWriter
  max_epochs: 1000
  log_every_n_steps: 1
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.01
lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: val_loss
    patience: 5 # check early stopping
model:
  class_path: LitModel
  init_args:
    backbone_type: Cnn14
    conv_type: PANNS
    input_channels: 1
    prototype_type: partial
    partial_len: 32000 # 1-second @ 32 kHz
    partial_overlap: 0.5
    prototype_h: 1
    prototype_w: 1
    n_prototypes_per_label: 12
    # pretrained_weights: /path/to/weights
data:
  class_path: LitData
  init_args:
    # dataset_path: /path/to/dataset
    sampling_rate: 32000
    batch_size: 128
    num_workers: 12
    prefetch_factor: 2
# pipeline_stage: learn-prototypes-supervised|project-prototypes-supervised|compute-embeddings|train-classifier
